name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint-and-test:
    name: Lint, Format Check & Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Biome lint
        run: pnpm lint

      - name: Run Biome format check
        run: pnpm check

      - name: Run tests
        run: pnpm test

      - name: Build application
        run: pnpm build
        
      - name: Check build output
        run: |
          echo "Build output structure:"
          ls -la .vinxi/ || echo ".vinxi directory not found"
          ls -la .output/ || echo ".output directory not found"
          
      - name: Security check - Verify no secrets in build
        run: |
          if grep -r "dev-secret-change-in-production" .vinxi/ 2>/dev/null; then
            echo "❌ Default secret found in build output!"
            exit 1
          fi
          echo "✅ No default secrets found in build"

  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build

      - name: Check build output for deployment
        run: |
          echo "Checking deployment directory:"
          ls -la .vinxi/build/client/ || echo ".vinxi/build/client directory not found"
          ls -la .vinxi/prerender/client/ || echo ".vinxi/prerender/client directory not found"
          ls -la .output/public/ || echo ".output/public directory not found"
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .vinxi/build/client --project-name=optibody --compatibility-date=2024-12-01